package com.example.demo.model;
// Generated May 8, 2019 11:38:39 PM by Hibernate Tools 5.1.7.Final

import com.fasterxml.jackson.annotation.JsonIgnore;
import org.springframework.format.annotation.DateTimeFormat;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Benhnhan generated by hbm2java
 */
@Entity
@Table(name = "benhnhan", catalog = "quanlysuco")
public class Benhnhan implements java.io.Serializable {

	private String mabenhnhan;
	private Donvitructhuoc donvitructhuoc;
	private String bnTen;
	private Integer bnTuoi;
	private Boolean bnGioitinh;
	private String bnSobhyt;
	private String bnCmnd;
	private String bnDiachi;
	private Date bnNgaytiepnhan;
	private Boolean bnTrangthai;
	private Set<PhieuSuCo> phieuSuCos = new HashSet<PhieuSuCo>(0);

	public Benhnhan() {
	}

	public Benhnhan(String mabenhnhan, Donvitructhuoc donvitructhuoc) {
		this.mabenhnhan = mabenhnhan;
		this.donvitructhuoc = donvitructhuoc;
	}
	public Benhnhan(String mabenhnhan, Donvitructhuoc donvitructhuoc, String bnTen, Integer bnTuoi, Boolean bnGioitinh,
					String bnSobhyt, String bnCmnd, String bnDiachi, Date bnNgaytiepnhan){
		this.mabenhnhan = mabenhnhan;
		this.donvitructhuoc = donvitructhuoc;
		this.bnTen = bnTen;
		this.bnTuoi = bnTuoi;
		this.bnGioitinh = bnGioitinh;
		this.bnSobhyt = bnSobhyt;
		this.bnCmnd = bnCmnd;
		this.bnDiachi = bnDiachi;
		this.bnNgaytiepnhan = bnNgaytiepnhan;
		this.bnTrangthai = true;
	}

	public Benhnhan(String mabenhnhan, Donvitructhuoc donvitructhuoc, String bnTen, Integer bnTuoi, Boolean bnGioitinh,
			String bnSobhyt, String bnCmnd, String bnDiachi, Date bnNgaytiepnhan, Boolean bnTrangthai,
			Set<PhieuSuCo> phieuSuCos) {
		this.mabenhnhan = mabenhnhan;
		this.donvitructhuoc = donvitructhuoc;
		this.bnTen = bnTen;
		this.bnTuoi = bnTuoi;
		this.bnGioitinh = bnGioitinh;
		this.bnSobhyt = bnSobhyt;
		this.bnCmnd = bnCmnd;
		this.bnDiachi = bnDiachi;
		this.bnNgaytiepnhan = bnNgaytiepnhan;
		this.bnTrangthai = bnTrangthai;
		this.phieuSuCos = phieuSuCos;
	}

	@Id

	@Column(name = "MABENHNHAN", unique = true, nullable = false, length = 25)
	public String getMabenhnhan() {
		return this.mabenhnhan;
	}

	public void setMabenhnhan(String mabenhnhan) {
		this.mabenhnhan = mabenhnhan;
	}

	@JsonIgnore
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DVTT", nullable = false)
	public Donvitructhuoc getDonvitructhuoc() {
		return this.donvitructhuoc;
	}

	public void setDonvitructhuoc(Donvitructhuoc donvitructhuoc) {
		this.donvitructhuoc = donvitructhuoc;
	}

	@Column(name = "BN_TEN", length = 50)
	public String getBnTen() {
		return this.bnTen;
	}

	public void setBnTen(String bnTen) {
		this.bnTen = bnTen;
	}

	@Column(name = "BN_TUOI")
	public Integer getBnTuoi() {
		return this.bnTuoi;
	}

	public void setBnTuoi(Integer bnTuoi) {
		this.bnTuoi = bnTuoi;
	}

	@Column(name = "BN_GIOITINH")
	public Boolean getBnGioitinh() {
		return this.bnGioitinh;
	}

	public void setBnGioitinh(Boolean bnGioitinh) {
		this.bnGioitinh = bnGioitinh;
	}

	@Column(name = "BN_SOBHYT")
	public String getBnSobhyt() {
		return this.bnSobhyt;
	}

	public void setBnSobhyt(String bnSobhyt) {
		this.bnSobhyt = bnSobhyt;
	}

	@Column(name = "BN_CMND")
	public String getBnCmnd() {
		return this.bnCmnd;
	}

	public void setBnCmnd(String bnCmnd) {
		this.bnCmnd = bnCmnd;
	}

	@Column(name = "BN_DIACHI")
	public String getBnDiachi() {
		return this.bnDiachi;
	}

	public void setBnDiachi(String bnDiachi) {
		this.bnDiachi = bnDiachi;
	}

//	@DateTimeFormat(pattern = "yyyy-MM-dd")

	@Column(name = "BN_NGAYTIEPNHAN", length = 19)
	public Date getBnNgaytiepnhan() {
		return this.bnNgaytiepnhan;
	}

	public void setBnNgaytiepnhan(Date bnNgaytiepnhan) {
		this.bnNgaytiepnhan = bnNgaytiepnhan;
	}

	@Column(name = "BN_TRANGTHAI")
	public Boolean getBnTrangthai() {
		return this.bnTrangthai;
	}

	public void setBnTrangthai(Boolean bnTrangthai) {
		this.bnTrangthai = bnTrangthai;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "benhnhan")
	public Set<PhieuSuCo> getPhieuSuCos() {
		return this.phieuSuCos;
	}

	public void setPhieuSuCos(Set<PhieuSuCo> phieuSuCos) {
		this.phieuSuCos = phieuSuCos;
	}

}
