package com.example.demo.model;
// Generated May 8, 2019 11:38:39 PM by Hibernate Tools 5.1.7.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ChitietquyenPhieusuco generated by hbm2java
 */
@Entity
@Table(name = "chitietquyen_phieusuco", catalog = "quanlysuco")
public class ChitietquyenPhieusuco implements java.io.Serializable {

	private ChitietquyenPhieusucoId id;
	private Nhanvien nhanvien;
	private Quyenhan quyenhan;
	private Boolean checked;

	public ChitietquyenPhieusuco() {
	}

	public ChitietquyenPhieusuco(ChitietquyenPhieusucoId id, Nhanvien nhanvien, Quyenhan quyenhan) {
		this.id = id;
		this.nhanvien = nhanvien;
		this.quyenhan = quyenhan;
	}

	public ChitietquyenPhieusuco(ChitietquyenPhieusucoId id, Nhanvien nhanvien, Quyenhan quyenhan, Boolean checked) {
		this.id = id;
		this.nhanvien = nhanvien;
		this.quyenhan = quyenhan;
		this.checked = checked;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "quyenMa", column = @Column(name = "QUYEN_MA", nullable = false)),
			@AttributeOverride(name = "nvMa", column = @Column(name = "NV_MA", nullable = false)) })
	public ChitietquyenPhieusucoId getId() {
		return this.id;
	}

	public void setId(ChitietquyenPhieusucoId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "NV_MA", nullable = false, insertable = false, updatable = false)
	public Nhanvien getNhanvien() {
		return this.nhanvien;
	}

	public void setNhanvien(Nhanvien nhanvien) {
		this.nhanvien = nhanvien;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "QUYEN_MA", nullable = false, insertable = false, updatable = false)
	public Quyenhan getQuyenhan() {
		return this.quyenhan;
	}

	public void setQuyenhan(Quyenhan quyenhan) {
		this.quyenhan = quyenhan;
	}

	@Column(name = "CHECKED")
	public Boolean getChecked() {
		return this.checked;
	}

	public void setChecked(Boolean checked) {
		this.checked = checked;
	}

}
