package com.example.demo.model;
// Generated May 8, 2019 11:38:39 PM by Hibernate Tools 5.1.7.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ChitietXulyId generated by hbm2java
 */
@Embeddable
public class ChitietXulyId implements java.io.Serializable {

	private int xulyMa;
	private int phieuMa;

	public ChitietXulyId() {
	}

	public ChitietXulyId(int xulyMa, int phieuMa) {
		this.xulyMa = xulyMa;
		this.phieuMa = phieuMa;
	}

	@Column(name = "XULY_MA", nullable = false)
	public int getXulyMa() {
		return this.xulyMa;
	}

	public void setXulyMa(int xulyMa) {
		this.xulyMa = xulyMa;
	}

	@Column(name = "PHIEU_MA", nullable = false)
	public int getPhieuMa() {
		return this.phieuMa;
	}

	public void setPhieuMa(int phieuMa) {
		this.phieuMa = phieuMa;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ChitietXulyId))
			return false;
		ChitietXulyId castOther = (ChitietXulyId) other;

		return (this.getXulyMa() == castOther.getXulyMa()) && (this.getPhieuMa() == castOther.getPhieuMa());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getXulyMa();
		result = 37 * result + this.getPhieuMa();
		return result;
	}

}
