package com.example.demo.model;
// Generated May 8, 2019 11:38:39 PM by Hibernate Tools 5.1.7.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ChitiethotroId generated by hbm2java
 */
@Embeddable
public class ChitiethotroId implements java.io.Serializable {

	private int ycMa;
	private int phieuMa;

	public ChitiethotroId() {
	}

	public ChitiethotroId(int ycMa, int phieuMa) {
		this.ycMa = ycMa;
		this.phieuMa = phieuMa;
	}

	@Column(name = "YC_MA", nullable = false)
	public int getYcMa() {
		return this.ycMa;
	}

	public void setYcMa(int ycMa) {
		this.ycMa = ycMa;
	}

	@Column(name = "PHIEU_MA", nullable = false)
	public int getPhieuMa() {
		return this.phieuMa;
	}

	public void setPhieuMa(int phieuMa) {
		this.phieuMa = phieuMa;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ChitiethotroId))
			return false;
		ChitiethotroId castOther = (ChitiethotroId) other;

		return (this.getYcMa() == castOther.getYcMa()) && (this.getPhieuMa() == castOther.getPhieuMa());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getYcMa();
		result = 37 * result + this.getPhieuMa();
		return result;
	}

}
