package com.example.demo.model;
// Generated May 8, 2019 11:38:39 PM by Hibernate Tools 5.1.7.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Chitiethotro generated by hbm2java
 */
@Entity
@Table(name = "chitiethotro", catalog = "quanlysuco")
public class Chitiethotro implements java.io.Serializable {

	private ChitiethotroId id;
	private PhieuSuCo phieuSuCo;
	private YeucauHotro yeucauHotro;
	private Boolean checked;
	private String noidung;

	public Chitiethotro() {
	}

	public Chitiethotro(ChitiethotroId id, PhieuSuCo phieuSuCo, YeucauHotro yeucauHotro) {
		this.id = id;
		this.phieuSuCo = phieuSuCo;
		this.yeucauHotro = yeucauHotro;
	}

	public Chitiethotro(ChitiethotroId id, PhieuSuCo phieuSuCo, YeucauHotro yeucauHotro, Boolean checked,
			String noidung) {
		this.id = id;
		this.phieuSuCo = phieuSuCo;
		this.yeucauHotro = yeucauHotro;
		this.checked = checked;
		this.noidung = noidung;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "ycMa", column = @Column(name = "YC_MA", nullable = false)),
			@AttributeOverride(name = "phieuMa", column = @Column(name = "PHIEU_MA", nullable = false)) })
	public ChitiethotroId getId() {
		return this.id;
	}

	public void setId(ChitiethotroId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PHIEU_MA", nullable = false, insertable = false, updatable = false)
	public PhieuSuCo getPhieuSuCo() {
		return this.phieuSuCo;
	}

	public void setPhieuSuCo(PhieuSuCo phieuSuCo) {
		this.phieuSuCo = phieuSuCo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "YC_MA", nullable = false, insertable = false, updatable = false)
	public YeucauHotro getYeucauHotro() {
		return this.yeucauHotro;
	}

	public void setYeucauHotro(YeucauHotro yeucauHotro) {
		this.yeucauHotro = yeucauHotro;
	}

	@Column(name = "CHECKED")
	public Boolean getChecked() {
		return this.checked;
	}

	public void setChecked(Boolean checked) {
		this.checked = checked;
	}

	@Column(name = "NOIDUNG", length = 65535)
	public String getNoidung() {
		return this.noidung;
	}

	public void setNoidung(String noidung) {
		this.noidung = noidung;
	}

}
