package com.example.demo.model;
// Generated May 8, 2019 11:38:39 PM by Hibernate Tools 5.1.7.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ChitiesucoId generated by hbm2java
 */
@Embeddable
public class ChitiesucoId implements java.io.Serializable {

	private int phieuMa;
	private int sucoMa;

	public ChitiesucoId() {
	}

	public ChitiesucoId(int phieuMa, int sucoMa) {
		this.phieuMa = phieuMa;
		this.sucoMa = sucoMa;
	}

	@Column(name = "PHIEU_MA", nullable = false)
	public int getPhieuMa() {
		return this.phieuMa;
	}

	public void setPhieuMa(int phieuMa) {
		this.phieuMa = phieuMa;
	}

	@Column(name = "SUCO_MA", nullable = false)
	public int getSucoMa() {
		return this.sucoMa;
	}

	public void setSucoMa(int sucoMa) {
		this.sucoMa = sucoMa;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ChitiesucoId))
			return false;
		ChitiesucoId castOther = (ChitiesucoId) other;

		return (this.getPhieuMa() == castOther.getPhieuMa()) && (this.getSucoMa() == castOther.getSucoMa());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getPhieuMa();
		result = 37 * result + this.getSucoMa();
		return result;
	}

}
