package com.example.demo.model;
// Generated May 8, 2019 11:38:39 PM by Hibernate Tools 5.1.7.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ChitietXuly generated by hbm2java
 */
@Entity
@Table(name = "chitiet_xuly", catalog = "quanlysuco")
public class ChitietXuly implements java.io.Serializable {

	private ChitietXulyId id;
	private PhieuSuCo phieuSuCo;
	private XulySuco xulySuco;
	private String noidung;

	public ChitietXuly() {
	}

	public ChitietXuly(ChitietXulyId id, PhieuSuCo phieuSuCo, XulySuco xulySuco) {
		this.id = id;
		this.phieuSuCo = phieuSuCo;
		this.xulySuco = xulySuco;
	}

	public ChitietXuly(ChitietXulyId id, PhieuSuCo phieuSuCo, XulySuco xulySuco, String noidung) {
		this.id = id;
		this.phieuSuCo = phieuSuCo;
		this.xulySuco = xulySuco;
		this.noidung = noidung;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "xulyMa", column = @Column(name = "XULY_MA", nullable = false)),
			@AttributeOverride(name = "phieuMa", column = @Column(name = "PHIEU_MA", nullable = false)) })
	public ChitietXulyId getId() {
		return this.id;
	}

	public void setId(ChitietXulyId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PHIEU_MA", nullable = false, insertable = false, updatable = false)
	public PhieuSuCo getPhieuSuCo() {
		return this.phieuSuCo;
	}

	public void setPhieuSuCo(PhieuSuCo phieuSuCo) {
		this.phieuSuCo = phieuSuCo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "XULY_MA", nullable = false, insertable = false, updatable = false)
	public XulySuco getXulySuco() {
		return this.xulySuco;
	}

	public void setXulySuco(XulySuco xulySuco) {
		this.xulySuco = xulySuco;
	}

	@Column(name = "NOIDUNG", length = 65535)
	public String getNoidung() {
		return this.noidung;
	}

	public void setNoidung(String noidung) {
		this.noidung = noidung;
	}

}
