package com.example.demo.model;
// Generated May 8, 2019 11:38:39 PM by Hibernate Tools 5.1.7.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Chitiesuco generated by hbm2java
 */
@Entity
@Table(name = "chitiesuco", catalog = "quanlysuco")
public class Chitiesuco implements java.io.Serializable {

	private ChitiesucoId id;
	private PhieuSuCo phieuSuCo;
	private ThongtinSuco thongtinSuco;
	private Boolean checked;

	public Chitiesuco() {
	}

	public Chitiesuco(ChitiesucoId id, PhieuSuCo phieuSuCo, ThongtinSuco thongtinSuco) {
		this.id = id;
		this.phieuSuCo = phieuSuCo;
		this.thongtinSuco = thongtinSuco;
	}

	public Chitiesuco(ChitiesucoId id, PhieuSuCo phieuSuCo, ThongtinSuco thongtinSuco, Boolean checked) {
		this.id = id;
		this.phieuSuCo = phieuSuCo;
		this.thongtinSuco = thongtinSuco;
		this.checked = checked;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "phieuMa", column = @Column(name = "PHIEU_MA", nullable = false)),
			@AttributeOverride(name = "sucoMa", column = @Column(name = "SUCO_MA", nullable = false)) })
	public ChitiesucoId getId() {
		return this.id;
	}

	public void setId(ChitiesucoId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PHIEU_MA", nullable = false, insertable = false, updatable = false)
	public PhieuSuCo getPhieuSuCo() {
		return this.phieuSuCo;
	}

	public void setPhieuSuCo(PhieuSuCo phieuSuCo) {
		this.phieuSuCo = phieuSuCo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SUCO_MA", nullable = false, insertable = false, updatable = false)
	public ThongtinSuco getThongtinSuco() {
		return this.thongtinSuco;
	}

	public void setThongtinSuco(ThongtinSuco thongtinSuco) {
		this.thongtinSuco = thongtinSuco;
	}

	@Column(name = "CHECKED")
	public Boolean getChecked() {
		return this.checked;
	}

	public void setChecked(Boolean checked) {
		this.checked = checked;
	}

}
