package com.example.demo.model;
// Generated May 8, 2019 11:38:39 PM by Hibernate Tools 5.1.7.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ChitietquyenPhieusucoId generated by hbm2java
 */
@Embeddable
public class ChitietquyenPhieusucoId implements java.io.Serializable {

	private int quyenMa;
	private int nvMa;

	public ChitietquyenPhieusucoId() {
	}

	public ChitietquyenPhieusucoId(int quyenMa, int nvMa) {
		this.quyenMa = quyenMa;
		this.nvMa = nvMa;
	}

	@Column(name = "QUYEN_MA", nullable = false)
	public int getQuyenMa() {
		return this.quyenMa;
	}

	public void setQuyenMa(int quyenMa) {
		this.quyenMa = quyenMa;
	}

	@Column(name = "NV_MA", nullable = false)
	public int getNvMa() {
		return this.nvMa;
	}

	public void setNvMa(int nvMa) {
		this.nvMa = nvMa;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ChitietquyenPhieusucoId))
			return false;
		ChitietquyenPhieusucoId castOther = (ChitietquyenPhieusucoId) other;

		return (this.getQuyenMa() == castOther.getQuyenMa()) && (this.getNvMa() == castOther.getNvMa());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getQuyenMa();
		result = 37 * result + this.getNvMa();
		return result;
	}

}
