package com.example.demo.model;
// Generated May 8, 2019 11:38:39 PM by Hibernate Tools 5.1.7.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Chucvu generated by hbm2java
 */
@Entity
@Table(name = "chucvu", catalog = "quanlysuco")
public class Chucvu implements java.io.Serializable {

	private Long cvMa;
	private String cvTen;
	private Boolean cvTrangthai;
	private Set<Nhanvien> nhanviens = new HashSet<Nhanvien>(0);

	public Chucvu() {
	}

	public Chucvu(String cvTen, Boolean cvTrangthai, Set<Nhanvien> nhanviens) {
		this.cvTen = cvTen;
		this.cvTrangthai = cvTrangthai;
		this.nhanviens = nhanviens;
	}
	public Chucvu(String cvTen){
		this.cvTen = cvTen;
		this.cvTrangthai = true;
	}
	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "CV_MA", unique = true, nullable = false)
	public Long getCvMa() {
		return this.cvMa;
	}

	public void setCvMa(Long cvMa) {
		this.cvMa = cvMa;
	}

	@Column(name = "CV_TEN", length = 50)
	public String getCvTen() {
		return this.cvTen;
	}

	public void setCvTen(String cvTen) {
		this.cvTen = cvTen;
	}

	@Column(name = "CV_TRANGTHAI")
	public Boolean getCvTrangthai() {
		return this.cvTrangthai;
	}

	public void setCvTrangthai(Boolean cvTrangthai) {
		this.cvTrangthai = cvTrangthai;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "chucvu")
	public Set<Nhanvien> getNhanviens() {
		return this.nhanviens;
	}

	public void setNhanviens(Set<Nhanvien> nhanviens) {
		this.nhanviens = nhanviens;
	}

}
