package com.example.demo.model;
// Generated May 8, 2019 11:38:39 PM by Hibernate Tools 5.1.7.Final

import com.fasterxml.jackson.annotation.JsonManagedReference;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Donvitructhuoc generated by hbm2java
 */
@Entity
@Table(name = "donvitructhuoc", catalog = "quanlysuco")
public class Donvitructhuoc implements java.io.Serializable {

	private String dvtt;
	private String dvttTen;
	private String dvttDiachi;
	private String dvttSdt;
	private Boolean dvttTrangthai;
	private Set<XulySuco> xulySucos = new HashSet<XulySuco>(0);
	private Set<ThongtinSuco> thongtinSucos = new HashSet<ThongtinSuco>(0);
	private Set<YeucauHotro> yeucauHotros = new HashSet<YeucauHotro>(0);
	private Set<Nhanvien> nhanviens = new HashSet<Nhanvien>(0);
	private Set<Khoa> khoas = new HashSet<Khoa>(0);
	private Set<Benhnhan> benhnhans = new HashSet<Benhnhan>(0);

	public Donvitructhuoc() {
	}

	public Donvitructhuoc(String dvtt) {
		this.dvtt = dvtt;
	}
	public Donvitructhuoc(String dvtt, String dvttTen, String dvttDiachi, String dvttSdt)
	{
		this.dvtt = dvtt;
		this.dvttTen = dvttTen;
		this.dvttDiachi = dvttDiachi;
		this.dvttSdt = dvttSdt;
		this.dvttTrangthai = true;
	}

	public Donvitructhuoc(String dvtt, String dvttTen, String dvttDiachi, String dvttSdt, Boolean dvttTrangthai,
			Set<XulySuco> xulySucos, Set<ThongtinSuco> thongtinSucos, Set<YeucauHotro> yeucauHotros,
			Set<Nhanvien> nhanviens, Set<Khoa> khoas, Set<Benhnhan> benhnhans) {
		this.dvtt = dvtt;
		this.dvttTen = dvttTen;
		this.dvttDiachi = dvttDiachi;
		this.dvttSdt = dvttSdt;
		this.dvttTrangthai = dvttTrangthai;
		this.xulySucos = xulySucos;
		this.thongtinSucos = thongtinSucos;
		this.yeucauHotros = yeucauHotros;
		this.nhanviens = nhanviens;
		this.khoas = khoas;
		this.benhnhans = benhnhans;
	}

	@Id

	@Column(name = "DVTT", unique = true, nullable = false, length = 50)
	public String getDvtt() {
		return this.dvtt;
	}

	public void setDvtt(String dvtt) {
		this.dvtt = dvtt;
	}

	@Column(name = "DVTT_TEN")
	public String getDvttTen() {
		return this.dvttTen;
	}

	public void setDvttTen(String dvttTen) {
		this.dvttTen = dvttTen;
	}

	@Column(name = "DVTT_DIACHI", length = 65535)
	public String getDvttDiachi() {
		return this.dvttDiachi;
	}

	public void setDvttDiachi(String dvttDiachi) {
		this.dvttDiachi = dvttDiachi;
	}

	@Column(name = "DVTT_SDT", length = 11)
	public String getDvttSdt() {
		return this.dvttSdt;
	}

	public void setDvttSdt(String dvttSdt) {
		this.dvttSdt = dvttSdt;
	}

	@Column(name = "DVTT_TRANGTHAI")
	public Boolean getDvttTrangthai() {
		return this.dvttTrangthai;
	}

	public void setDvttTrangthai(Boolean dvttTrangthai) {
		this.dvttTrangthai = dvttTrangthai;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "donvitructhuoc")
	public Set<XulySuco> getXulySucos() {
		return this.xulySucos;
	}

	public void setXulySucos(Set<XulySuco> xulySucos) {
		this.xulySucos = xulySucos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "donvitructhuoc")
	public Set<ThongtinSuco> getThongtinSucos() {
		return this.thongtinSucos;
	}

	public void setThongtinSucos(Set<ThongtinSuco> thongtinSucos) {
		this.thongtinSucos = thongtinSucos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "donvitructhuoc")
	public Set<YeucauHotro> getYeucauHotros() {
		return this.yeucauHotros;
	}

	public void setYeucauHotros(Set<YeucauHotro> yeucauHotros) {
		this.yeucauHotros = yeucauHotros;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "donvitructhuoc")
	public Set<Nhanvien> getNhanviens() {
		return this.nhanviens;
	}

	public void setNhanviens(Set<Nhanvien> nhanviens) {
		this.nhanviens = nhanviens;
	}


	@OneToMany(fetch = FetchType.LAZY, mappedBy = "donvitructhuoc")
	public Set<Khoa> getKhoas() {
		return this.khoas;
	}

	public void setKhoas(Set<Khoa> khoas) {
		this.khoas = khoas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "donvitructhuoc")
	public Set<Benhnhan> getBenhnhans() {
		return this.benhnhans;
	}

	public void setBenhnhans(Set<Benhnhan> benhnhans) {
		this.benhnhans = benhnhans;
	}

}
