package com.example.demo.model;
// Generated May 8, 2019 11:38:39 PM by Hibernate Tools 5.1.7.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * KhoaGiaiQuyetSuCoId generated by hbm2java
 */
@Embeddable
public class KhoaGiaiQuyetSuCoId implements java.io.Serializable {

	private int phieuMa;
	private int khoaMa;

	public KhoaGiaiQuyetSuCoId() {
	}

	public KhoaGiaiQuyetSuCoId(int phieuMa, int khoaMa) {
		this.phieuMa = phieuMa;
		this.khoaMa = khoaMa;
	}

	@Column(name = "PHIEU_MA", nullable = false)
	public int getPhieuMa() {
		return this.phieuMa;
	}

	public void setPhieuMa(int phieuMa) {
		this.phieuMa = phieuMa;
	}

	@Column(name = "KHOA_MA", nullable = false)
	public int getKhoaMa() {
		return this.khoaMa;
	}

	public void setKhoaMa(int khoaMa) {
		this.khoaMa = khoaMa;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof KhoaGiaiQuyetSuCoId))
			return false;
		KhoaGiaiQuyetSuCoId castOther = (KhoaGiaiQuyetSuCoId) other;

		return (this.getPhieuMa() == castOther.getPhieuMa()) && (this.getKhoaMa() == castOther.getKhoaMa());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getPhieuMa();
		result = 37 * result + this.getKhoaMa();
		return result;
	}

}
