package com.example.demo.model;
// Generated May 8, 2019 11:38:39 PM by Hibernate Tools 5.1.7.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Loainhanvien generated by hbm2java
 */
@Entity
@Table(name = "loainhanvien", catalog = "quanlysuco")
public class Loainhanvien implements java.io.Serializable {

	private Long lnvMa;
	private String lnvTen;
	private Boolean lnvTrangthai;
	private Set<Nhanvien> nhanviens = new HashSet<Nhanvien>(0);

	public Loainhanvien( String lnvTen) {
		this.lnvTen = lnvTen;
		this.lnvTrangthai = true;
	}
	public  Loainhanvien(){

	}

	public Loainhanvien(String lnvTen, Boolean lnvTrangthai, Set<Nhanvien> nhanviens) {
		this.lnvTen = lnvTen;
		this.lnvTrangthai = lnvTrangthai;
		this.nhanviens = nhanviens;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "LNV_MA", unique = true, nullable = false)
	public Long getLnvMa() {
		return this.lnvMa;
	}

	public void setLnvMa(Long lnvMa) {
		this.lnvMa = lnvMa;
	}

	@Column(name = "LNV_TEN", length = 30)
	public String getLnvTen() {
		return this.lnvTen;
	}

	public void setLnvTen(String lnvTen) {
		this.lnvTen = lnvTen;
	}

	@Column(name = "LNV_TRANGTHAI")
	public Boolean getLnvTrangthai() {
		return this.lnvTrangthai;
	}

	public void setLnvTrangthai(Boolean lnvTrangthai) {
		this.lnvTrangthai = lnvTrangthai;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "loainhanvien")
	public Set<Nhanvien> getNhanviens() {
		return this.nhanviens;
	}

	public void setNhanviens(Set<Nhanvien> nhanviens) {
		this.nhanviens = nhanviens;
	}

}
