package com.example.demo.model;
// Generated May 8, 2019 11:38:39 PM by Hibernate Tools 5.1.7.Final

import com.fasterxml.jackson.annotation.JsonIgnore;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PhieuSuCo generated by hbm2java
 */
@Entity
@Table(name = "phieu_su_co", catalog = "quanlysuco")
public class PhieuSuCo implements java.io.Serializable {

	private Long phieuMa;
	private Benhnhan benhnhan;
	private Nhanvien nhanvien;
	private Date phieuNgaysuco;
	private String phieuMota;
	private String phieuDiadiem;
	private Boolean phieuSuconghiemtrong;
	private String lichsuChinhsua;
	private Boolean phieuGiauten;
	private Boolean phieuTrangthaiduyet;
	private Boolean phieuLaphdhc;
	private Boolean bienban;
	private String bienbanNoidung;
	private Set<ChitietXuly> chitietXulies = new HashSet<ChitietXuly>(0);
	private Set<KhoaGiaiQuyetSuCo> khoaGiaiQuyetSuCos = new HashSet<KhoaGiaiQuyetSuCo>(0);
	private Set<Chitiethotro> chitiethotros = new HashSet<Chitiethotro>(0);
	private Set<Chitiesuco> chitiesucos = new HashSet<Chitiesuco>(0);

	public PhieuSuCo(Benhnhan benhnhan, Nhanvien nhanvien, Date phieuNgaysuco, String phieuMota, String phieuDiadiem,
					 Boolean phieuSuconghiemtrong, String lichsuChinhsua, Boolean phieuGiauten, Boolean phieuLaphdhc, Boolean bienban)
	{
		this.benhnhan = benhnhan;
		this.nhanvien = nhanvien;
		this.phieuNgaysuco = phieuNgaysuco;
		this.phieuMota = phieuMota;
		this.phieuDiadiem = phieuDiadiem;
		this.phieuSuconghiemtrong = phieuSuconghiemtrong;
		this.lichsuChinhsua = lichsuChinhsua;
		this.phieuGiauten = phieuGiauten;
		this.phieuLaphdhc = phieuLaphdhc;
		this.bienban = bienban;
		this.phieuTrangthaiduyet = false;
	}
	public PhieuSuCo() {
	}

	public PhieuSuCo(Benhnhan benhnhan, Nhanvien nhanvien) {
		this.benhnhan = benhnhan;
		this.nhanvien = nhanvien;
	}


	public PhieuSuCo(Benhnhan benhnhan, Nhanvien nhanvien, Date phieuNgaysuco, String phieuMota, String phieuDiadiem,
			Boolean phieuSuconghiemtrong, String lichsuChinhsua, Boolean phieuGiauten, Boolean phieuTrangthaiduyet,
			Boolean phieuLaphdhc, Boolean bienban, String bienbanNoidung, Set<ChitietXuly> chitietXulies,
			Set<KhoaGiaiQuyetSuCo> khoaGiaiQuyetSuCos, Set<Chitiethotro> chitiethotros, Set<Chitiesuco> chitiesucos) {
		this.benhnhan = benhnhan;
		this.nhanvien = nhanvien;
		this.phieuNgaysuco = phieuNgaysuco;
		this.phieuMota = phieuMota;
		this.phieuDiadiem = phieuDiadiem;
		this.phieuSuconghiemtrong = phieuSuconghiemtrong;
		this.lichsuChinhsua = lichsuChinhsua;
		this.phieuGiauten = phieuGiauten;
		this.phieuTrangthaiduyet = phieuTrangthaiduyet;
		this.phieuLaphdhc = phieuLaphdhc;
		this.bienban = bienban;
		this.bienbanNoidung = bienbanNoidung;
		this.chitietXulies = chitietXulies;
		this.khoaGiaiQuyetSuCos = khoaGiaiQuyetSuCos;
		this.chitiethotros = chitiethotros;
		this.chitiesucos = chitiesucos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "PHIEU_MA", unique = true, nullable = false)
	public Long getPhieuMa() {
		return this.phieuMa;
	}

	public void setPhieuMa(Long phieuMa) {
		this.phieuMa = phieuMa;
	}

	@JsonIgnore
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MABENHNHAN", nullable = false)
	public Benhnhan getBenhnhan() {
		return this.benhnhan;
	}

	public void setBenhnhan(Benhnhan benhnhan) {
		this.benhnhan = benhnhan;
	}

	@JsonIgnore
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "NV_MA", nullable = false)
	public Nhanvien getNhanvien() {
		return this.nhanvien;
	}

	public void setNhanvien(Nhanvien nhanvien) {
		this.nhanvien = nhanvien;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "PHIEU_NGAYSUCO", length = 19)
	public Date getPhieuNgaysuco() {
		return this.phieuNgaysuco;
	}

	public void setPhieuNgaysuco(Date phieuNgaysuco) {
		this.phieuNgaysuco = phieuNgaysuco;
	}

	@Column(name = "PHIEU_MOTA", length = 65535)
	public String getPhieuMota() {
		return this.phieuMota;
	}

	public void setPhieuMota(String phieuMota) {
		this.phieuMota = phieuMota;
	}

	@Column(name = "PHIEU_DIADIEM", length = 65535)
	public String getPhieuDiadiem() {
		return this.phieuDiadiem;
	}

	public void setPhieuDiadiem(String phieuDiadiem) {
		this.phieuDiadiem = phieuDiadiem;
	}

	@Column(name = "PHIEU_SUCONGHIEMTRONG")
	public Boolean getPhieuSuconghiemtrong() {
		return this.phieuSuconghiemtrong;
	}

	public void setPhieuSuconghiemtrong(Boolean phieuSuconghiemtrong) {
		this.phieuSuconghiemtrong = phieuSuconghiemtrong;
	}

	@Column(name = "LICHSU_CHINHSUA", length = 65535)
	public String getLichsuChinhsua() {
		return this.lichsuChinhsua;
	}

	public void setLichsuChinhsua(String lichsuChinhsua) {
		this.lichsuChinhsua = lichsuChinhsua;
	}

	@Column(name = "PHIEU_GIAUTEN")
	public Boolean getPhieuGiauten() {
		return this.phieuGiauten;
	}

	public void setPhieuGiauten(Boolean phieuGiauten) {
		this.phieuGiauten = phieuGiauten;
	}

	@Column(name = "PHIEU_TRANGTHAIDUYET")
	public Boolean getPhieuTrangthaiduyet() {
		return this.phieuTrangthaiduyet;
	}

	public void setPhieuTrangthaiduyet(Boolean phieuTrangthaiduyet) {
		this.phieuTrangthaiduyet = phieuTrangthaiduyet;
	}

	@Column(name = "PHIEU_LAPHDHC")
	public Boolean getPhieuLaphdhc() {
		return this.phieuLaphdhc;
	}

	public void setPhieuLaphdhc(Boolean phieuLaphdhc) {
		this.phieuLaphdhc = phieuLaphdhc;
	}

	@Column(name = "BIENBAN")
	public Boolean getBienban() {
		return this.bienban;
	}

	public void setBienban(Boolean bienban) {
		this.bienban = bienban;
	}

	@Column(name = "BIENBAN_NOIDUNG", length = 65535)
	public String getBienbanNoidung() {
		return this.bienbanNoidung;
	}

	public void setBienbanNoidung(String bienbanNoidung) {
		this.bienbanNoidung = bienbanNoidung;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "phieuSuCo")
	public Set<ChitietXuly> getChitietXulies() {
		return this.chitietXulies;
	}

	public void setChitietXulies(Set<ChitietXuly> chitietXulies) {
		this.chitietXulies = chitietXulies;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "phieuSuCo")
	public Set<KhoaGiaiQuyetSuCo> getKhoaGiaiQuyetSuCos() {
		return this.khoaGiaiQuyetSuCos;
	}

	public void setKhoaGiaiQuyetSuCos(Set<KhoaGiaiQuyetSuCo> khoaGiaiQuyetSuCos) {
		this.khoaGiaiQuyetSuCos = khoaGiaiQuyetSuCos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "phieuSuCo")
	public Set<Chitiethotro> getChitiethotros() {
		return this.chitiethotros;
	}

	public void setChitiethotros(Set<Chitiethotro> chitiethotros) {
		this.chitiethotros = chitiethotros;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "phieuSuCo")
	public Set<Chitiesuco> getChitiesucos() {
		return this.chitiesucos;
	}

	public void setChitiesucos(Set<Chitiesuco> chitiesucos) {
		this.chitiesucos = chitiesucos;
	}

}
