package com.example.demo.model;
// Generated May 8, 2019 11:38:39 PM by Hibernate Tools 5.1.7.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Quyenhan generated by hbm2java
 */
@Entity
@Table(name = "quyenhan", catalog = "quanlysuco")
public class Quyenhan implements java.io.Serializable {

	private Integer quyenMa;
	private String quyenTen;
	private Boolean quyenTrangthai;
	private Set<ChitietquyenPhieusuco> chitietquyenPhieusucos = new HashSet<ChitietquyenPhieusuco>(0);

	public Quyenhan() {
	}

	public Quyenhan(String quyenTen, Boolean quyenTrangthai, Set<ChitietquyenPhieusuco> chitietquyenPhieusucos) {
		this.quyenTen = quyenTen;
		this.quyenTrangthai = quyenTrangthai;
		this.chitietquyenPhieusucos = chitietquyenPhieusucos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "QUYEN_MA", unique = true, nullable = false)
	public Integer getQuyenMa() {
		return this.quyenMa;
	}

	public void setQuyenMa(Integer quyenMa) {
		this.quyenMa = quyenMa;
	}

	@Column(name = "QUYEN_TEN", length = 50)
	public String getQuyenTen() {
		return this.quyenTen;
	}

	public void setQuyenTen(String quyenTen) {
		this.quyenTen = quyenTen;
	}

	@Column(name = "QUYEN_TRANGTHAI")
	public Boolean getQuyenTrangthai() {
		return this.quyenTrangthai;
	}

	public void setQuyenTrangthai(Boolean quyenTrangthai) {
		this.quyenTrangthai = quyenTrangthai;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "quyenhan")
	public Set<ChitietquyenPhieusuco> getChitietquyenPhieusucos() {
		return this.chitietquyenPhieusucos;
	}

	public void setChitietquyenPhieusucos(Set<ChitietquyenPhieusuco> chitietquyenPhieusucos) {
		this.chitietquyenPhieusucos = chitietquyenPhieusucos;
	}

}
