package com.example.demo.model;
// Generated May 8, 2019 11:38:39 PM by Hibernate Tools 5.1.7.Final

import com.fasterxml.jackson.annotation.JsonIgnore;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ThongtinSuco generated by hbm2java
 */
@Entity
@Table(name = "thongtin_suco", catalog = "quanlysuco")
public class ThongtinSuco implements java.io.Serializable {

	private Integer sucoMa;
	private Donvitructhuoc donvitructhuoc;
	private String sucoTen;
	private Boolean sucoTrangthai;
	private Set<Chitiesuco> chitiesucos = new HashSet<Chitiesuco>(0);

	public ThongtinSuco() {
	}

	public ThongtinSuco(Donvitructhuoc donvitructhuoc) {
		this.donvitructhuoc = donvitructhuoc;
	}

	public ThongtinSuco(Donvitructhuoc donvitructhuoc, String sucoTen, Boolean sucoTrangthai,
			Set<Chitiesuco> chitiesucos) {
		this.donvitructhuoc = donvitructhuoc;
		this.sucoTen = sucoTen;
		this.sucoTrangthai = sucoTrangthai;
		this.chitiesucos = chitiesucos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "SUCO_MA", unique = true, nullable = false)
	public Integer getSucoMa() {
		return this.sucoMa;
	}

	public void setSucoMa(Integer sucoMa) {
		this.sucoMa = sucoMa;
	}

	@JsonIgnore
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DVTT", nullable = false)
	public Donvitructhuoc getDonvitructhuoc() {
		return this.donvitructhuoc;
	}

	public void setDonvitructhuoc(Donvitructhuoc donvitructhuoc) {
		this.donvitructhuoc = donvitructhuoc;
	}

	@Column(name = "SUCO_TEN")
	public String getSucoTen() {
		return this.sucoTen;
	}

	public void setSucoTen(String sucoTen) {
		this.sucoTen = sucoTen;
	}

	@Column(name = "SUCO_TRANGTHAI")
	public Boolean getSucoTrangthai() {
		return this.sucoTrangthai;
	}

	public void setSucoTrangthai(Boolean sucoTrangthai) {
		this.sucoTrangthai = sucoTrangthai;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "thongtinSuco")
	public Set<Chitiesuco> getChitiesucos() {
		return this.chitiesucos;
	}

	public void setChitiesucos(Set<Chitiesuco> chitiesucos) {
		this.chitiesucos = chitiesucos;
	}

}
