package com.example.demo.model;
// Generated May 8, 2019 11:38:39 PM by Hibernate Tools 5.1.7.Final

import com.fasterxml.jackson.annotation.JsonIgnore;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * XulySuco generated by hbm2java
 */
@Entity
@Table(name = "xuly_suco", catalog = "quanlysuco")
public class XulySuco implements java.io.Serializable {

	private Integer xulyMa;
	private Donvitructhuoc donvitructhuoc;
	private String xulyTen;
	private Boolean xulyTrangthai;
	private Set<ChitietXuly> chitietXulies = new HashSet<ChitietXuly>(0);

	public XulySuco() {
	}

	public XulySuco(Donvitructhuoc donvitructhuoc) {
		this.donvitructhuoc = donvitructhuoc;
	}

	public XulySuco(Donvitructhuoc donvitructhuoc, String xulyTen, Boolean xulyTrangthai,
			Set<ChitietXuly> chitietXulies) {
		this.donvitructhuoc = donvitructhuoc;
		this.xulyTen = xulyTen;
		this.xulyTrangthai = xulyTrangthai;
		this.chitietXulies = chitietXulies;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "XULY_MA", unique = true, nullable = false)
	public Integer getXulyMa() {
		return this.xulyMa;
	}

	public void setXulyMa(Integer xulyMa) {
		this.xulyMa = xulyMa;
	}

	@JsonIgnore
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DVTT", nullable = false)
	public Donvitructhuoc getDonvitructhuoc() {
		return this.donvitructhuoc;
	}

	public void setDonvitructhuoc(Donvitructhuoc donvitructhuoc) {
		this.donvitructhuoc = donvitructhuoc;
	}

	@Column(name = "XULY_TEN", length = 50)
	public String getXulyTen() {
		return this.xulyTen;
	}

	public void setXulyTen(String xulyTen) {
		this.xulyTen = xulyTen;
	}

	@Column(name = "XULY_TRANGTHAI")
	public Boolean getXulyTrangthai() {
		return this.xulyTrangthai;
	}

	public void setXulyTrangthai(Boolean xulyTrangthai) {
		this.xulyTrangthai = xulyTrangthai;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "xulySuco")
	public Set<ChitietXuly> getChitietXulies() {
		return this.chitietXulies;
	}

	public void setChitietXulies(Set<ChitietXuly> chitietXulies) {
		this.chitietXulies = chitietXulies;
	}

}
