package com.example.demo.model;
// Generated May 8, 2019 11:38:39 PM by Hibernate Tools 5.1.7.Final

import com.fasterxml.jackson.annotation.JsonIgnore;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * YeucauHotro generated by hbm2java
 */
@Entity
@Table(name = "yeucau_hotro", catalog = "quanlysuco")
public class YeucauHotro implements java.io.Serializable {

	private Integer ycMa;
	private Donvitructhuoc donvitructhuoc;
	private String ycTen;
	private Boolean ycTrangthai;
	private Set<Chitiethotro> chitiethotros = new HashSet<Chitiethotro>(0);

	public YeucauHotro() {
	}

	public YeucauHotro(Donvitructhuoc donvitructhuoc) {
		this.donvitructhuoc = donvitructhuoc;
	}

	public YeucauHotro(Donvitructhuoc donvitructhuoc, String ycTen, Boolean ycTrangthai,
			Set<Chitiethotro> chitiethotros) {
		this.donvitructhuoc = donvitructhuoc;
		this.ycTen = ycTen;
		this.ycTrangthai = ycTrangthai;
		this.chitiethotros = chitiethotros;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "YC_MA", unique = true, nullable = false)
	public Integer getYcMa() {
		return this.ycMa;
	}

	public void setYcMa(Integer ycMa) {
		this.ycMa = ycMa;
	}

	@JsonIgnore
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DVTT", nullable = false)
	public Donvitructhuoc getDonvitructhuoc() {
		return this.donvitructhuoc;
	}

	public void setDonvitructhuoc(Donvitructhuoc donvitructhuoc) {
		this.donvitructhuoc = donvitructhuoc;
	}

	@Column(name = "YC_TEN", length = 50)
	public String getYcTen() {
		return this.ycTen;
	}

	public void setYcTen(String ycTen) {
		this.ycTen = ycTen;
	}

	@Column(name = "YC_TRANGTHAI")
	public Boolean getYcTrangthai() {
		return this.ycTrangthai;
	}

	public void setYcTrangthai(Boolean ycTrangthai) {
		this.ycTrangthai = ycTrangthai;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "yeucauHotro")
	public Set<Chitiethotro> getChitiethotros() {
		return this.chitiethotros;
	}

	public void setChitiethotros(Set<Chitiethotro> chitiethotros) {
		this.chitiethotros = chitiethotros;
	}

}
